//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "drive_folder_shares")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub folder_id: Uuid,
    pub shared_with_user_id: Option<Uuid>,
    #[sea_orm(unique)]
    pub share_token: Option<String>,
    pub permission: super::super::drive_folder_shares::SharePermission,
    pub created_by: Uuid,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "folder_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub drive_folders: HasOne<super::drive_folders::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "created_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users_2: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "shared_with_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users_1: HasOne<super::users::Entity>,
}
