//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "forge_webhook_deliveries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_forge_webhook_deliveries_delivery")]
    pub host: String,
    #[sea_orm(unique_key = "uq_forge_webhook_deliveries_delivery")]
    pub host_url: String,
    #[sea_orm(unique_key = "uq_forge_webhook_deliveries_delivery")]
    pub delivery_id: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
