//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "forge_commits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_forge_commits_repo_sha")]
    pub project_id: Uuid,
    #[sea_orm(unique_key = "uq_forge_commits_repo_sha")]
    pub host: String,
    #[sea_orm(unique_key = "uq_forge_commits_repo_sha")]
    pub host_url: String,
    #[sea_orm(unique_key = "uq_forge_commits_repo_sha")]
    pub repo_owner: String,
    #[sea_orm(unique_key = "uq_forge_commits_repo_sha")]
    pub repo_name: String,
    #[sea_orm(unique_key = "uq_forge_commits_repo_sha")]
    pub sha: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub author_handle: String,
    pub author_name: String,
    pub committed_at: DateTimeWithTimeZone,
    pub html_url: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub projects: HasOne<super::projects::Entity>,
    #[sea_orm(has_many, via = "forge_commit_links")]
    pub tasks: HasMany<super::tasks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
