//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "notifications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "notifications_user_id_dedupe_key_key")]
    pub user_id: Uuid,
    pub task_id: Option<Uuid>,
    pub notification_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    pub read_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub project_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub target: Json,
    #[sea_orm(unique_key = "notifications_user_id_dedupe_key_key")]
    pub dedupe_key: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tasks: HasOne<super::tasks::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
