//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_statuses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "project_statuses_project_id_name_key")]
    pub project_id: Uuid,
    #[sea_orm(unique_key = "project_statuses_project_id_name_key")]
    pub name: String,
    pub color: String,
    pub position: i16,
    pub is_default: bool,
    pub is_done_state: bool,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub projects: HasOne<super::projects::Entity>,
    #[sea_orm(has_many)]
    pub tasks: HasMany<super::tasks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
