//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "review_findings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub review_id: Uuid,
    pub severity: super::super::review_findings::FindingSeverity,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    #[sea_orm(nullable)]
    pub file: Option<String>,
    #[sea_orm(nullable)]
    pub line: Option<i32>,
    pub state: super::super::review_findings::FindingState,
    #[sea_orm(nullable)]
    pub deferred_task_id: Option<Uuid>,
    #[sea_orm(nullable)]
    pub fixed_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "review_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub reviews: HasOne<super::reviews::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
