//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "reviews")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "reviews_project_id_repo_owner_repo_name_pr_number_round_key")]
    pub project_id: Uuid,
    #[sea_orm(nullable)]
    pub integration_id: Option<Uuid>,
    #[sea_orm(unique_key = "reviews_project_id_repo_owner_repo_name_pr_number_round_key")]
    pub repo_owner: String,
    #[sea_orm(unique_key = "reviews_project_id_repo_owner_repo_name_pr_number_round_key")]
    pub repo_name: String,
    #[sea_orm(unique_key = "reviews_project_id_repo_owner_repo_name_pr_number_round_key")]
    pub pr_number: i32,
    #[sea_orm(unique_key = "reviews_project_id_repo_owner_repo_name_pr_number_round_key")]
    pub round: i32,
    pub head_sha: String,
    pub reviewer_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(nullable)]
    pub pr_title: Option<String>,
    #[sea_orm(nullable)]
    pub pr_author: Option<String>,
    #[sea_orm(nullable)]
    pub pr_head_sha: Option<String>,
    #[sea_orm(nullable)]
    pub pr_head_checked_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(nullable)]
    pub summary_comment_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub projects: HasOne<super::projects::Entity>,
    #[sea_orm(
        belongs_to,
        from = "integration_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub github_integrations: HasOne<super::github_integrations::Entity>,
    #[sea_orm(
        belongs_to,
        from = "reviewer_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
