//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "review_finding_transitions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub finding_id: Uuid,
    pub actor_id: Uuid,
    #[sea_orm(nullable)]
    pub from_state: Option<super::super::review_findings::FindingState>,
    pub to_state: super::super::review_findings::FindingState,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "finding_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub review_findings: HasOne<super::review_findings::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
