//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "webhook_deliveries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub webhook_id: Uuid,
    pub event: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    pub status_code: Option<i32>,
    pub attempt: i16,
    pub next_attempt_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub delivered_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "webhook_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub webhooks: HasOne<super::webhooks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
