packages:
  - apps/cli
  - apps/frontend
  - packages/*
sharedWorkspaceLockfile: false
allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@sentry/cli': true
  esbuild: true
  vue-demi: true
catalog:
  rollup-plugin-visualizer: 7.0.0
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
minimumReleaseAgeExclude:
  - '@koyori-app/openapi-vue-query'
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - '@vitest/coverage-v8'
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
saveExact: true
catalogMode: prefer
