allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@sentry/cli': true
  esbuild: true
  vue-demi: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.24
  vite-plus: 0.1.21
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - '@vitest/coverage-v8'
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
saveExact: true
