/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectRole } from './ProjectRole';
import {
    ProjectRoleFromJSON,
    ProjectRoleFromJSONTyped,
    ProjectRoleToJSON,
    ProjectRoleToJSONTyped,
} from './ProjectRole';

/**
 * 
 * @export
 * @interface AddMemberRequest
 */
export interface AddMemberRequest {
    /**
     * 
     * @type {ProjectRole}
     * @memberof AddMemberRequest
     */
    role: ProjectRole;
    /**
     * 
     * @type {string}
     * @memberof AddMemberRequest
     */
    userId: string;
}



/**
 * Check if a given object implements the AddMemberRequest interface.
 */
export function instanceOfAddMemberRequest(value: object): value is AddMemberRequest {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AddMemberRequestFromJSON(json: any): AddMemberRequest {
    return AddMemberRequestFromJSONTyped(json, false);
}

export function AddMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': ProjectRoleFromJSON(json['role']),
        'userId': json['user_id'],
    };
}

export function AddMemberRequestToJSON(json: any): AddMemberRequest {
    return AddMemberRequestToJSONTyped(json, false);
}

export function AddMemberRequestToJSONTyped(value?: AddMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': ProjectRoleToJSON(value['role']),
        'user_id': value['userId'],
    };
}

