/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrateEntitiesProjectsModel
 */
export interface CrateEntitiesProjectsModel {
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesProjectsModel
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesProjectsModel
     */
    iconEmoji?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesProjectsModel
     */
    iconUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesProjectsModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesProjectsModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesProjectsModel
     */
    tenantId: string;
}

/**
 * Check if a given object implements the CrateEntitiesProjectsModel interface.
 */
export function instanceOfCrateEntitiesProjectsModel(value: object): value is CrateEntitiesProjectsModel {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function CrateEntitiesProjectsModelFromJSON(json: any): CrateEntitiesProjectsModel {
    return CrateEntitiesProjectsModelFromJSONTyped(json, false);
}

export function CrateEntitiesProjectsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrateEntitiesProjectsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'iconEmoji': json['icon_emoji'] == null ? undefined : json['icon_emoji'],
        'iconUrl': json['icon_url'] == null ? undefined : json['icon_url'],
        'id': json['id'],
        'name': json['name'],
        'tenantId': json['tenant_id'],
    };
}

export function CrateEntitiesProjectsModelToJSON(json: any): CrateEntitiesProjectsModel {
    return CrateEntitiesProjectsModelToJSONTyped(json, false);
}

export function CrateEntitiesProjectsModelToJSONTyped(value?: CrateEntitiesProjectsModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'icon_emoji': value['iconEmoji'],
        'icon_url': value['iconUrl'],
        'id': value['id'],
        'name': value['name'],
        'tenant_id': value['tenantId'],
    };
}

