/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrateEntitiesUsersModel
 */
export interface CrateEntitiesUsersModel {
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesUsersModel
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesUsersModel
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesUsersModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesUsersModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesUsersModel
     */
    username: string;
}

/**
 * Check if a given object implements the CrateEntitiesUsersModel interface.
 */
export function instanceOfCrateEntitiesUsersModel(value: object): value is CrateEntitiesUsersModel {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CrateEntitiesUsersModelFromJSON(json: any): CrateEntitiesUsersModel {
    return CrateEntitiesUsersModelFromJSONTyped(json, false);
}

export function CrateEntitiesUsersModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrateEntitiesUsersModel {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'email': json['email'],
        'id': json['id'],
        'username': json['username'],
    };
}

export function CrateEntitiesUsersModelToJSON(json: any): CrateEntitiesUsersModel {
    return CrateEntitiesUsersModelToJSONTyped(json, false);
}

export function CrateEntitiesUsersModelToJSONTyped(value?: CrateEntitiesUsersModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar_url': value['avatarUrl'],
        'bio': value['bio'],
        'email': value['email'],
        'id': value['id'],
        'username': value['username'],
    };
}

