/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrateEntitiesTenantsModel
 */
export interface CrateEntitiesTenantsModel {
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesTenantsModel
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesTenantsModel
     */
    displayId: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesTenantsModel
     */
    iconUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesTenantsModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesTenantsModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesTenantsModel
     */
    ownerId: string;
}

/**
 * Check if a given object implements the CrateEntitiesTenantsModel interface.
 */
export function instanceOfCrateEntitiesTenantsModel(value: object): value is CrateEntitiesTenantsModel {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('displayId' in value) || value['displayId'] === undefined) return false;
    if (!('iconUrl' in value) || value['iconUrl'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    return true;
}

export function CrateEntitiesTenantsModelFromJSON(json: any): CrateEntitiesTenantsModel {
    return CrateEntitiesTenantsModelFromJSONTyped(json, false);
}

export function CrateEntitiesTenantsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrateEntitiesTenantsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'displayId': json['display_id'],
        'iconUrl': json['icon_url'],
        'id': json['id'],
        'name': json['name'],
        'ownerId': json['owner_id'],
    };
}

export function CrateEntitiesTenantsModelToJSON(json: any): CrateEntitiesTenantsModel {
    return CrateEntitiesTenantsModelToJSONTyped(json, false);
}

export function CrateEntitiesTenantsModelToJSONTyped(value?: CrateEntitiesTenantsModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'display_id': value['displayId'],
        'icon_url': value['iconUrl'],
        'id': value['id'],
        'name': value['name'],
        'owner_id': value['ownerId'],
    };
}

