/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectRole } from './ProjectRole';
import {
    ProjectRoleFromJSON,
    ProjectRoleFromJSONTyped,
    ProjectRoleToJSON,
    ProjectRoleToJSONTyped,
} from './ProjectRole';

/**
 * 
 * @export
 * @interface CrateEntitiesProjectMembersModel
 */
export interface CrateEntitiesProjectMembersModel {
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesProjectMembersModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesProjectMembersModel
     */
    projectId: string;
    /**
     * 
     * @type {ProjectRole}
     * @memberof CrateEntitiesProjectMembersModel
     */
    role: ProjectRole;
    /**
     * 
     * @type {string}
     * @memberof CrateEntitiesProjectMembersModel
     */
    userId: string;
}



/**
 * Check if a given object implements the CrateEntitiesProjectMembersModel interface.
 */
export function instanceOfCrateEntitiesProjectMembersModel(value: object): value is CrateEntitiesProjectMembersModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CrateEntitiesProjectMembersModelFromJSON(json: any): CrateEntitiesProjectMembersModel {
    return CrateEntitiesProjectMembersModelFromJSONTyped(json, false);
}

export function CrateEntitiesProjectMembersModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrateEntitiesProjectMembersModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'role': ProjectRoleFromJSON(json['role']),
        'userId': json['user_id'],
    };
}

export function CrateEntitiesProjectMembersModelToJSON(json: any): CrateEntitiesProjectMembersModel {
    return CrateEntitiesProjectMembersModelToJSONTyped(json, false);
}

export function CrateEntitiesProjectMembersModelToJSONTyped(value?: CrateEntitiesProjectMembersModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project_id': value['projectId'],
        'role': ProjectRoleToJSON(value['role']),
        'user_id': value['userId'],
    };
}

