/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectRequest
 */
export interface CreateProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateProjectRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectRequest
     */
    iconEmoji?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectRequest
     */
    iconUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateProjectRequest interface.
 */
export function instanceOfCreateProjectRequest(value: object): value is CreateProjectRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateProjectRequestFromJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestFromJSONTyped(json, false);
}

export function CreateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'iconEmoji': json['icon_emoji'] == null ? undefined : json['icon_emoji'],
        'iconUrl': json['icon_url'] == null ? undefined : json['icon_url'],
        'name': json['name'],
    };
}

export function CreateProjectRequestToJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestToJSONTyped(json, false);
}

export function CreateProjectRequestToJSONTyped(value?: CreateProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'icon_emoji': value['iconEmoji'],
        'icon_url': value['iconUrl'],
        'name': value['name'],
    };
}

