/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Scope } from './Scope';
import {
    ScopeFromJSON,
    ScopeFromJSONTyped,
    ScopeToJSON,
    ScopeToJSONTyped,
} from './Scope';

/**
 * PAT 作成時のレスポンス（平文トークンはこの応答でのみ返却）
 * @export
 * @interface CreatePersonalTokenResponse
 */
export interface CreatePersonalTokenResponse {
    /**
     * 
     * @type {Date}
     * @memberof CreatePersonalTokenResponse
     */
    expiresAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonalTokenResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof CreatePersonalTokenResponse
     */
    lastUsedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonalTokenResponse
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePersonalTokenResponse
     */
    revoked: boolean;
    /**
     * アクセストークン等に付与する権限スコープのリスト。
     * @type {Array<Scope>}
     * @memberof CreatePersonalTokenResponse
     */
    scopes: Array<Scope>;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonalTokenResponse
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonalTokenResponse
     */
    tokenLastFour: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonalTokenResponse
     */
    userId: string;
}

/**
 * Check if a given object implements the CreatePersonalTokenResponse interface.
 */
export function instanceOfCreatePersonalTokenResponse(value: object): value is CreatePersonalTokenResponse {
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lastUsedAt' in value) || value['lastUsedAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('revoked' in value) || value['revoked'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('tokenLastFour' in value) || value['tokenLastFour'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CreatePersonalTokenResponseFromJSON(json: any): CreatePersonalTokenResponse {
    return CreatePersonalTokenResponseFromJSONTyped(json, false);
}

export function CreatePersonalTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePersonalTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': (json['expires_at'] == null ? null : new Date(json['expires_at'])),
        'id': json['id'],
        'lastUsedAt': (json['last_used_at'] == null ? null : new Date(json['last_used_at'])),
        'name': json['name'],
        'revoked': json['revoked'],
        'scopes': ((json['scopes'] as Array<any>).map(ScopeFromJSON)),
        'token': json['token'],
        'tokenLastFour': json['token_last_four'],
        'userId': json['user_id'],
    };
}

export function CreatePersonalTokenResponseToJSON(json: any): CreatePersonalTokenResponse {
    return CreatePersonalTokenResponseToJSONTyped(json, false);
}

export function CreatePersonalTokenResponseToJSONTyped(value?: CreatePersonalTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'id': value['id'],
        'last_used_at': value['lastUsedAt'] == null ? value['lastUsedAt'] : value['lastUsedAt'].toISOString(),
        'name': value['name'],
        'revoked': value['revoked'],
        'scopes': ((value['scopes'] as Array<any>).map(ScopeToJSON)),
        'token': value['token'],
        'token_last_four': value['tokenLastFour'],
        'user_id': value['userId'],
    };
}

