/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTenantRequest
 */
export interface CreateTenantRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTenantRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenantRequest
     */
    displayId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenantRequest
     */
    iconUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenantRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateTenantRequest interface.
 */
export function instanceOfCreateTenantRequest(value: object): value is CreateTenantRequest {
    if (!('displayId' in value) || value['displayId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateTenantRequestFromJSON(json: any): CreateTenantRequest {
    return CreateTenantRequestFromJSONTyped(json, false);
}

export function CreateTenantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTenantRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'displayId': json['display_id'],
        'iconUrl': json['icon_url'] == null ? undefined : json['icon_url'],
        'name': json['name'],
    };
}

export function CreateTenantRequestToJSON(json: any): CreateTenantRequest {
    return CreateTenantRequestToJSONTyped(json, false);
}

export function CreateTenantRequestToJSONTyped(value?: CreateTenantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'display_id': value['displayId'],
        'icon_url': value['iconUrl'],
        'name': value['name'],
    };
}

