/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Login403Response
 */
export interface Login403Response {
    /**
     * 
     * @type {string}
     * @memberof Login403Response
     */
    message: string;
}

/**
 * Check if a given object implements the Login403Response interface.
 */
export function instanceOfLogin403Response(value: object): value is Login403Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function Login403ResponseFromJSON(json: any): Login403Response {
    return Login403ResponseFromJSONTyped(json, false);
}

export function Login403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Login403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function Login403ResponseToJSON(json: any): Login403Response {
    return Login403ResponseToJSONTyped(json, false);
}

export function Login403ResponseToJSONTyped(value?: Login403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

