/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * API 共通のエラー応答ボディ。
 * @export
 * @interface Login401Response
 */
export interface Login401Response {
    /**
     * 
     * @type {string}
     * @memberof Login401Response
     */
    message: string;
}

/**
 * Check if a given object implements the Login401Response interface.
 */
export function instanceOfLogin401Response(value: object): value is Login401Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function Login401ResponseFromJSON(json: any): Login401Response {
    return Login401ResponseFromJSONTyped(json, false);
}

export function Login401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Login401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function Login401ResponseToJSON(json: any): Login401Response {
    return Login401ResponseToJSONTyped(json, false);
}

export function Login401ResponseToJSONTyped(value?: Login401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

