/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Scope = {
    ReadUser: 'read:user',
    WriteUser: 'write:user',
    AdminAll: 'admin:all'
} as const;
export type Scope = typeof Scope[keyof typeof Scope];


export function instanceOfScope(value: any): boolean {
    for (const key in Scope) {
        if (Object.prototype.hasOwnProperty.call(Scope, key)) {
            if (Scope[key as keyof typeof Scope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScopeFromJSON(json: any): Scope {
    return ScopeFromJSONTyped(json, false);
}

export function ScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scope {
    return json as Scope;
}

export function ScopeToJSON(value?: Scope | null): any {
    return value as any;
}

export function ScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): Scope {
    return value as Scope;
}

