/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProjectRequest
 */
export interface UpdateProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    iconEmoji?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    iconUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    name?: string | null;
}

/**
 * Check if a given object implements the UpdateProjectRequest interface.
 */
export function instanceOfUpdateProjectRequest(value: object): value is UpdateProjectRequest {
    return true;
}

export function UpdateProjectRequestFromJSON(json: any): UpdateProjectRequest {
    return UpdateProjectRequestFromJSONTyped(json, false);
}

export function UpdateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'iconEmoji': json['icon_emoji'] == null ? undefined : json['icon_emoji'],
        'iconUrl': json['icon_url'] == null ? undefined : json['icon_url'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateProjectRequestToJSON(json: any): UpdateProjectRequest {
    return UpdateProjectRequestToJSONTyped(json, false);
}

export function UpdateProjectRequestToJSONTyped(value?: UpdateProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'icon_emoji': value['iconEmoji'],
        'icon_url': value['iconUrl'],
        'name': value['name'],
    };
}

