/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTenantRequest
 */
export interface UpdateTenantRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantRequest
     */
    iconUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantRequest
     */
    name?: string | null;
}

/**
 * Check if a given object implements the UpdateTenantRequest interface.
 */
export function instanceOfUpdateTenantRequest(value: object): value is UpdateTenantRequest {
    return true;
}

export function UpdateTenantRequestFromJSON(json: any): UpdateTenantRequest {
    return UpdateTenantRequestFromJSONTyped(json, false);
}

export function UpdateTenantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTenantRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'iconUrl': json['icon_url'] == null ? undefined : json['icon_url'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateTenantRequestToJSON(json: any): UpdateTenantRequest {
    return UpdateTenantRequestToJSONTyped(json, false);
}

export function UpdateTenantRequestToJSONTyped(value?: UpdateTenantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'icon_url': value['iconUrl'],
        'name': value['name'],
    };
}

