/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectRole } from './ProjectRole';
import {
    ProjectRoleFromJSON,
    ProjectRoleFromJSONTyped,
    ProjectRoleToJSON,
    ProjectRoleToJSONTyped,
} from './ProjectRole';

/**
 * 
 * @export
 * @interface UpdateMemberRequest
 */
export interface UpdateMemberRequest {
    /**
     * 
     * @type {ProjectRole}
     * @memberof UpdateMemberRequest
     */
    role: ProjectRole;
}



/**
 * Check if a given object implements the UpdateMemberRequest interface.
 */
export function instanceOfUpdateMemberRequest(value: object): value is UpdateMemberRequest {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UpdateMemberRequestFromJSON(json: any): UpdateMemberRequest {
    return UpdateMemberRequestFromJSONTyped(json, false);
}

export function UpdateMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': ProjectRoleFromJSON(json['role']),
    };
}

export function UpdateMemberRequestToJSON(json: any): UpdateMemberRequest {
    return UpdateMemberRequestToJSONTyped(json, false);
}

export function UpdateMemberRequestToJSONTyped(value?: UpdateMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': ProjectRoleToJSON(value['role']),
    };
}

