/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * メールでの本人確認時に送信する情報。
 * @export
 * @interface VerifyEmailRequest
 */
export interface VerifyEmailRequest {
    /**
     * メールまたはアプリにお知らせした認証用文字列です。
     * @type {string}
     * @memberof VerifyEmailRequest
     */
    token: string;
}

/**
 * Check if a given object implements the VerifyEmailRequest interface.
 */
export function instanceOfVerifyEmailRequest(value: object): value is VerifyEmailRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function VerifyEmailRequestFromJSON(json: any): VerifyEmailRequest {
    return VerifyEmailRequestFromJSONTyped(json, false);
}

export function VerifyEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function VerifyEmailRequestToJSON(json: any): VerifyEmailRequest {
    return VerifyEmailRequestToJSONTyped(json, false);
}

export function VerifyEmailRequestToJSONTyped(value?: VerifyEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

