/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CrateEntitiesLabelsModel,
    CrateEntitiesLabelsModelFromJSON,
    CrateEntitiesLabelsModelToJSON,
} from '../models/CrateEntitiesLabelsModel';
import {
    type CrateEntitiesUsersModel,
    CrateEntitiesUsersModelFromJSON,
    CrateEntitiesUsersModelToJSON,
} from '../models/CrateEntitiesUsersModel';
import {
    type CreatePersonalTokenResponse,
    CreatePersonalTokenResponseFromJSON,
    CreatePersonalTokenResponseToJSON,
} from '../models/CreatePersonalTokenResponse';
import {
    type Login401Response,
    Login401ResponseFromJSON,
    Login401ResponseToJSON,
} from '../models/Login401Response';
import {
    type LoginRequest,
    LoginRequestFromJSON,
    LoginRequestToJSON,
} from '../models/LoginRequest';
import {
    type PersonalTokenResponse,
    PersonalTokenResponseFromJSON,
    PersonalTokenResponseToJSON,
} from '../models/PersonalTokenResponse';
import {
    type RegisterRequest,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
} from '../models/RegisterRequest';
import {
    type ResendVerificationRequest,
    ResendVerificationRequestFromJSON,
    ResendVerificationRequestToJSON,
} from '../models/ResendVerificationRequest';
import {
    type VerifyEmailRequest,
    VerifyEmailRequestFromJSON,
    VerifyEmailRequestToJSON,
} from '../models/VerifyEmailRequest';

export interface CreatePersonalTokenRequest {
    body: object;
}

export interface GetPersonalTokenRequest {
    id: string;
}

export interface LoginOperationRequest {
    loginRequest: LoginRequest;
}

export interface RegisterOperationRequest {
    registerRequest: RegisterRequest;
}

export interface ResendVerificationEmailRequest {
    resendVerificationRequest: ResendVerificationRequest;
}

export interface RevokePersonalTokenRequest {
    id: string;
}

export interface VerifyEmailOperationRequest {
    verifyEmailRequest: VerifyEmailRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPersonalToken without sending the request
     */
    async createPersonalTokenRequestOpts(requestParameters: CreatePersonalTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createPersonalToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/personal_tokens`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * パーソナルアクセストークンを発行
     */
    async createPersonalTokenRaw(requestParameters: CreatePersonalTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePersonalTokenResponse>> {
        const requestOptions = await this.createPersonalTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePersonalTokenResponseFromJSON(jsonValue));
    }

    /**
     * パーソナルアクセストークンを発行
     */
    async createPersonalToken(requestParameters: CreatePersonalTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePersonalTokenResponse> {
        const response = await this.createPersonalTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getLabels without sending the request
     */
    async getLabelsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/labels`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ラベル一覧
     */
    async getLabelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CrateEntitiesLabelsModel>>> {
        const requestOptions = await this.getLabelsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CrateEntitiesLabelsModelFromJSON));
    }

    /**
     * ラベル一覧
     */
    async getLabels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CrateEntitiesLabelsModel>> {
        const response = await this.getLabelsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPersonalToken without sending the request
     */
    async getPersonalTokenRequestOpts(requestParameters: GetPersonalTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPersonalToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/personal_tokens/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したトークンを参照
     */
    async getPersonalTokenRaw(requestParameters: GetPersonalTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonalTokenResponse>> {
        const requestOptions = await this.getPersonalTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonalTokenResponseFromJSON(jsonValue));
    }

    /**
     * 指定したトークンを参照
     */
    async getPersonalToken(requestParameters: GetPersonalTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonalTokenResponse> {
        const response = await this.getPersonalTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for login without sending the request
     */
    async loginRequestOpts(requestParameters: LoginOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        };
    }

    /**
     * ログイン
     */
    async loginRaw(requestParameters: LoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.loginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ログイン
     */
    async login(requestParameters: LoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.loginRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for logout without sending the request
     */
    async logoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ログアウト
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.logoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ログアウト
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.logoutRaw(initOverrides);
    }

    /**
     * Creates request options for me without sending the request
     */
    async meRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ログイン中ユーザー情報
     */
    async meRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrateEntitiesUsersModel>> {
        const requestOptions = await this.meRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CrateEntitiesUsersModelFromJSON(jsonValue));
    }

    /**
     * ログイン中ユーザー情報
     */
    async me(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrateEntitiesUsersModel> {
        const response = await this.meRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for register without sending the request
     */
    async registerRequestOpts(requestParameters: RegisterOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        };
    }

    /**
     * 新規登録
     */
    async registerRaw(requestParameters: RegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.registerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 新規登録
     */
    async register(requestParameters: RegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resendVerificationEmail without sending the request
     */
    async resendVerificationEmailRequestOpts(requestParameters: ResendVerificationEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resendVerificationRequest'] == null) {
            throw new runtime.RequiredError(
                'resendVerificationRequest',
                'Required parameter "resendVerificationRequest" was null or undefined when calling resendVerificationEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/resend-verification-email`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResendVerificationRequestToJSON(requestParameters['resendVerificationRequest']),
        };
    }

    /**
     * 認証メールの再送
     */
    async resendVerificationEmailRaw(requestParameters: ResendVerificationEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.resendVerificationEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 認証メールの再送
     */
    async resendVerificationEmail(requestParameters: ResendVerificationEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.resendVerificationEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeAllPersonalTokens without sending the request
     */
    async revokeAllPersonalTokensRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/personal_tokens`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * すべての個人用トークンを取り消し
     */
    async revokeAllPersonalTokensRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PersonalTokenResponse>>> {
        const requestOptions = await this.revokeAllPersonalTokensRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PersonalTokenResponseFromJSON));
    }

    /**
     * すべての個人用トークンを取り消し
     */
    async revokeAllPersonalTokens(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PersonalTokenResponse>> {
        const response = await this.revokeAllPersonalTokensRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokePersonalToken without sending the request
     */
    async revokePersonalTokenRequestOpts(requestParameters: RevokePersonalTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revokePersonalToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/personal_tokens/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したトークンを取り消し
     */
    async revokePersonalTokenRaw(requestParameters: RevokePersonalTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonalTokenResponse>> {
        const requestOptions = await this.revokePersonalTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonalTokenResponseFromJSON(jsonValue));
    }

    /**
     * 指定したトークンを取り消し
     */
    async revokePersonalToken(requestParameters: RevokePersonalTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonalTokenResponse> {
        const response = await this.revokePersonalTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyEmail without sending the request
     */
    async verifyEmailRequestOpts(requestParameters: VerifyEmailOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['verifyEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyEmailRequest',
                'Required parameter "verifyEmailRequest" was null or undefined when calling verifyEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/verify-email`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyEmailRequestToJSON(requestParameters['verifyEmailRequest']),
        };
    }

    /**
     * メールアドレスの確認
     */
    async verifyEmailRaw(requestParameters: VerifyEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.verifyEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * メールアドレスの確認
     */
    async verifyEmail(requestParameters: VerifyEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.verifyEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
