use utoipa_axum::router::OpenApiRouter;
use utoipa_axum::routes;

use crate::AppState;

pub fn routes() -> OpenApiRouter<AppState> {
    OpenApiRouter::<AppState>::new()
        .routes(routes!(crate::handlers::tenants::list_tenants))
        .routes(routes!(crate::handlers::tenants::create_tenant))
        .routes(routes!(crate::handlers::tenants::get_tenant))
        .routes(routes!(crate::handlers::tenants::update_tenant))
        .routes(routes!(crate::handlers::tenants::delete_tenant))
        .routes(routes!(crate::handlers::auth_2fa::set_tenant_require_2fa))
        .nest(
            "/{tenant_id}/drive/folders",
            crate::routes::drive::tenant_folder_routes(),
        )
        .nest(
            "/{tenant_id}/projects",
            OpenApiRouter::<AppState>::new()
                .routes(routes!(crate::handlers::projects::list_projects))
                .routes(routes!(crate::handlers::projects::create_project))
                .routes(routes!(crate::handlers::projects::get_project))
                .routes(routes!(crate::handlers::projects::update_project))
                .routes(routes!(crate::handlers::projects::delete_project))
                .nest(
                    "/{project_id}/members",
                    OpenApiRouter::<AppState>::new()
                        .routes(routes!(crate::handlers::project_members::list_members))
                        .routes(routes!(crate::handlers::project_members::add_member))
                        .routes(routes!(crate::handlers::project_members::update_member))
                        .routes(routes!(crate::handlers::project_members::remove_member)),
                )
                .nest(
                    "/{project_id}/tasks",
                    OpenApiRouter::<AppState>::new()
                        .routes(routes!(crate::handlers::tasks::list_tasks))
                        .routes(routes!(crate::handlers::tasks::create_task))
                        .routes(routes!(crate::handlers::tasks::get_task))
                        .routes(routes!(crate::handlers::tasks::update_task))
                        .routes(routes!(crate::handlers::tasks::delete_task))
                        .routes(routes!(crate::handlers::tasks::archive_task))
                        .routes(routes!(crate::handlers::tasks::unarchive_task))
                        .routes(routes!(crate::handlers::tasks::list_assignees))
                        .routes(routes!(crate::handlers::tasks::add_assignee))
                        .routes(routes!(crate::handlers::tasks::update_assignee))
                        .routes(routes!(crate::handlers::tasks::remove_assignee))
                        .routes(routes!(crate::handlers::tasks::list_relations))
                        .routes(routes!(crate::handlers::tasks::add_relation))
                        .routes(routes!(crate::handlers::tasks::remove_relation))
                        .routes(routes!(crate::handlers::task_comments::list_comments))
                        .routes(routes!(crate::handlers::task_comments::create_comment))
                        .routes(routes!(crate::handlers::task_comments::update_comment))
                        .routes(routes!(crate::handlers::task_comments::delete_comment))
                        .routes(routes!(crate::handlers::task_comments::list_activities))
                        .routes(routes!(crate::handlers::time_tracking::get_time_summary))
                        .routes(routes!(crate::handlers::time_tracking::list_time_logs))
                        .routes(routes!(crate::handlers::time_tracking::create_time_log))
                        .routes(routes!(crate::handlers::time_tracking::update_time_log))
                        .routes(routes!(crate::handlers::time_tracking::delete_time_log))
                        .routes(routes!(crate::handlers::time_tracking::start_timer))
                        .routes(routes!(crate::handlers::time_tracking::stop_timer))
                        .routes(routes!(crate::handlers::time_tracking::get_timer_status))
                        .routes(routes!(crate::handlers::task_notifications::list_watchers))
                        .routes(routes!(crate::handlers::task_notifications::start_watch))
                        .routes(routes!(crate::handlers::task_notifications::stop_watch)),
                )
                .nest(
                    "/{project_id}/statuses",
                    OpenApiRouter::<AppState>::new()
                        .routes(routes!(crate::handlers::statuses::list_statuses))
                        .routes(routes!(crate::handlers::statuses::create_status))
                        .routes(routes!(crate::handlers::statuses::update_status))
                        .routes(routes!(crate::handlers::statuses::reorder_statuses))
                        .routes(routes!(crate::handlers::statuses::delete_status)),
                )
                .nest(
                    "/{project_id}/milestones",
                    OpenApiRouter::<AppState>::new()
                        .routes(routes!(crate::handlers::milestones::list_milestones))
                        .routes(routes!(crate::handlers::milestones::create_milestone))
                        .routes(routes!(crate::handlers::milestones::get_milestone))
                        .routes(routes!(crate::handlers::milestones::update_milestone))
                        .routes(routes!(crate::handlers::milestones::delete_milestone)),
                )
                .nest(
                    "/{project_id}/sprints",
                    OpenApiRouter::<AppState>::new()
                        .routes(routes!(crate::handlers::sprints::list_sprints))
                        .routes(routes!(crate::handlers::sprints::create_sprint))
                        .routes(routes!(crate::handlers::sprints::get_sprint))
                        .routes(routes!(crate::handlers::sprints::update_sprint))
                        .routes(routes!(crate::handlers::sprints::delete_sprint))
                        .routes(routes!(crate::handlers::sprints::start_sprint))
                        .routes(routes!(crate::handlers::sprints::complete_sprint))
                        .routes(routes!(crate::handlers::sprints::assign_tasks_to_sprint)),
                )
                .nest(
                    "/{project_id}/custom-fields",
                    OpenApiRouter::<AppState>::new()
                        .routes(routes!(crate::handlers::custom_fields::list_custom_fields))
                        .routes(routes!(crate::handlers::custom_fields::create_custom_field))
                        .routes(routes!(crate::handlers::custom_fields::update_custom_field))
                        .routes(routes!(crate::handlers::custom_fields::delete_custom_field)),
                )
                .nest(
                    "/{project_id}/labels",
                    OpenApiRouter::<AppState>::new()
                        .routes(routes!(crate::handlers::labels::list_labels))
                        .routes(routes!(crate::handlers::labels::create_label))
                        .routes(routes!(crate::handlers::labels::update_label))
                        .routes(routes!(crate::handlers::labels::delete_label))
                        .routes(routes!(crate::handlers::labels::export_labels))
                        .routes(routes!(crate::handlers::labels::import_labels)),
                )
                .nest(
                    "/{project_id}/github",
                    crate::routes::github::tenant_github_routes(),
                ),
        )
        .nest(
            "/{tenant_id}/drive",
            crate::routes::drive::tenant_drive_routes(),
        )
        .nest(
            "/{tenant_id}/users/me",
            OpenApiRouter::<AppState>::new()
                .routes(routes!(crate::handlers::my_tasks::get_personal_project))
                .routes(routes!(crate::handlers::my_tasks::list_my_tasks))
                .routes(routes!(crate::handlers::my_tasks::create_my_task)),
        )
}
