//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use utoipa::ToSchema;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "audit_logs")]
#[schema(as = crate::entities::audit_logs::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(nullable)]
    #[schema(nullable, value_type = Option<String>, format = "uuid")]
    pub actor_id: Option<Uuid>,
    pub actor_type: String,
    pub action: String,
    pub resource_type: String,
    pub resource_id: String,
    #[sea_orm(nullable)]
    #[schema(nullable, value_type = Option<String>, format = "uuid")]
    pub tenant_id: Option<Uuid>,
    #[sea_orm(nullable)]
    #[schema(nullable, value_type = Option<serde_json::Value>)]
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub ip_address: Option<String>,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub user_agent: Option<String>,
    #[schema(value_type = String, format = "date-time")]
    pub created_at: DateTimeUtc,
}

impl ActiveModelBehavior for ActiveModel {}
