//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "drive_folders")]
#[schema(as = crate::entities::drive_folders::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(nullable)]
    #[schema(value_type = String, format = "uuid", nullable)]
    pub parent_id: Option<Uuid>,
    #[schema(value_type = String, format = "uuid")]
    pub tenant_id: Uuid,
    #[sea_orm(nullable)]
    #[schema(value_type = String, format = "uuid", nullable)]
    pub project_id: Option<Uuid>,
    #[schema(value_type = String, format = "uuid")]
    pub created_by: Uuid,
    #[schema(value_type = String, format = "date-time")]
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeUtc,
}

impl ActiveModelBehavior for ActiveModel {}
