//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use crate::entities::drive_files::StorageType;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "drive_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub size: i64,
    pub mime_type: String,
    pub storage_type: StorageType,
    pub storage_key: String,
    pub tenant_id: Uuid,
    #[sea_orm(nullable)]
    pub project_id: Option<Uuid>,
    pub uploader_id: Uuid,
    #[sea_orm(nullable)]
    pub folder_id: Option<Uuid>,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
}
