//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::entities::drive_folder_shares::SharePermission;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "drive_folder_shares")]
#[schema(as = crate::entities::drive_folder_shares::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    pub folder_id: Uuid,
    #[sea_orm(nullable)]
    #[schema(value_type = String, format = "uuid", nullable)]
    pub shared_with_user_id: Option<Uuid>,
    #[sea_orm(nullable, unique)]
    #[schema(nullable)]
    #[sea_orm(unique)]
    pub share_token: Option<String>,
    pub permission: SharePermission,
    #[schema(value_type = String, format = "uuid")]
    pub created_by: Uuid,
    #[sea_orm(nullable)]
    #[schema(value_type = String, format = "date-time", nullable)]
    pub expires_at: Option<DateTimeUtc>,
    #[schema(value_type = String, format = "date-time")]
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeUtc,
}
