//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use crate::entities::drive_folder_shares::SharePermission;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "drive_folder_shares")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub folder_id: Uuid,
    #[sea_orm(nullable)]
    pub shared_with_user_id: Option<Uuid>,
    #[sea_orm(nullable, unique)]
    #[sea_orm(unique)]
    pub share_token: Option<String>,
    pub permission: SharePermission,
    pub created_by: Uuid,
    #[sea_orm(nullable)]
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
}
