//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "github_integrations")]
#[schema(as = crate::entities::github_integrations::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(unique)]
    pub project_id: Uuid,
    pub installation_id: i64,
    pub repo_owner: String,
    pub repo_name: String,
    #[schema(ignore)]
    #[serde(skip_serializing)]
    pub access_token_enc: String,
    #[schema(value_type = String, format = "date-time")]
    pub token_expires_at: DateTimeUtc,
    #[schema(value_type = String, format = "uuid")]
    pub created_by: Uuid,
    #[schema(value_type = String, format = "date-time")]
    pub created_at: DateTimeUtc,
}

impl ActiveModelBehavior for ActiveModel {}
