//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod labels;
pub mod notification_settings;
pub mod project_statuses;
pub mod project_task_counters;
pub mod projects;
pub mod recovery_codes;
pub mod system_settings;
pub mod task_assignees;
pub mod task_custom_field_values;
pub mod task_labels;
pub mod task_relations;
pub mod task_timers;
pub mod task_watchers;
pub mod tenants;
pub mod totp_credentials;
pub mod users;
