//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod labels;
pub mod project_statuses;
pub mod project_task_counters;
pub mod recovery_codes;
pub mod system_settings;
pub mod task_relations;
pub mod tenants;
pub mod totp_credentials;
pub mod users;
