//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "notifications")]
#[schema(as = crate::entities::notifications::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    pub user_id: Uuid,
    #[sea_orm(nullable)]
    #[schema(nullable, value_type = Option<String>, format = "uuid")]
    pub task_id: Option<Uuid>,
    pub notification_type: String,
    #[schema(value_type = serde_json::Value)]
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    #[sea_orm(nullable)]
    #[schema(nullable, value_type = Option<String>, format = "date-time")]
    pub read_at: Option<DateTimeUtc>,
    #[schema(value_type = String, format = "date-time")]
    pub created_at: DateTimeUtc,
}

impl ActiveModelBehavior for ActiveModel {}
