//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "oauth_connections")]
#[schema(as = crate::entities::oauth_connections::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    pub user_id: Uuid,
    pub provider: String,
    pub provider_user_id: String,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub provider_email: Option<String>,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub instance_url: Option<String>,
    #[sea_orm(nullable)]
    #[schema(ignore)]
    #[serde(skip_serializing)]
    pub access_token_enc: Option<String>,
    #[sea_orm(nullable)]
    #[schema(ignore)]
    #[serde(skip_serializing)]
    pub refresh_token_enc: Option<String>,
    #[sea_orm(nullable)]
    #[schema(value_type = String, format = "date-time", nullable)]
    pub token_expires_at: Option<DateTimeUtc>,
    #[schema(value_type = String, format = "date-time")]
    pub created_at: DateTimeUtc,
    #[schema(value_type = String, format = "date-time")]
    pub updated_at: DateTimeUtc,
}

impl ActiveModelBehavior for ActiveModel {}
