//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "oauth_connections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub provider: String,
    pub provider_user_id: String,
    #[sea_orm(nullable)]
    pub provider_email: Option<String>,
    #[sea_orm(nullable)]
    pub instance_url: Option<String>,
    #[sea_orm(nullable)]
    pub access_token_enc: Option<String>,
    #[sea_orm(nullable)]
    pub refresh_token_enc: Option<String>,
    #[sea_orm(nullable)]
    pub token_expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
