//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "passkeys")]
#[schema(as = crate::entities::passkeys::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    pub user_id: Uuid,
    #[schema(ignore)]
    #[serde(skip_serializing)]
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub credential_id: Vec<u8>,
    #[schema(ignore)]
    #[serde(skip_serializing)]
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub public_key: Vec<u8>,
    #[schema(ignore)]
    #[serde(skip_serializing)]
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub aaguid: Option<Vec<u8>>,
    pub sign_count: i64,
    pub name: String,
    #[sea_orm(nullable)]
    #[schema(value_type = String, format = "date-time", nullable)]
    pub last_used_at: Option<DateTimeUtc>,
    #[schema(value_type = String, format = "date-time")]
    pub created_at: DateTimeUtc,
}

impl ActiveModelBehavior for ActiveModel {}
