//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use crate::entities::scopes::ScopeList;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "personal_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub token_last_four: String,
    #[sea_orm(indexed)]
    pub token_hash: String,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub last_used_at: Option<DateTimeWithTimeZone>,
    pub revoked: bool,
    pub user_id: Uuid,
    pub scopes: ScopeList,
    pub tenant_id: Uuid,
    pub allowed_project_ids: Option<serde_json::Value>,
}

impl ActiveModelBehavior for ActiveModel {}
