//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

use crate::entities::scopes::ScopeList;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "personal_tokens")]
#[schema(as = crate::entities::personal_tokens::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub token_last_four: String,
    #[sea_orm(indexed)]
    #[schema(ignore)]
    #[serde(skip_serializing)]
    pub token_hash: String,
    #[schema(value_type = String, format = "date-time", nullable)]
    pub expires_at: Option<DateTimeUtc>,
    #[schema(value_type = String, format = "date-time", nullable)]
    pub last_used_at: Option<DateTimeUtc>,
    pub revoked: bool,
    #[schema(value_type = String, format = "uuid")]
    pub user_id: Uuid,
    pub scopes: ScopeList,
    #[schema(value_type = String, format = "uuid")]
    pub tenant_id: Uuid,
    /// JSONB として保存（`NULL` = テナント内全プロジェクト）。復元は `parse_allowed_project_ids`。
    pub allowed_project_ids: Option<serde_json::Value>,
}

impl ActiveModelBehavior for ActiveModel {}
