//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

use crate::entities::project_custom_fields::CustomFieldType;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "project_custom_fields")]
#[schema(as = crate::entities::project_custom_fields::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    pub project_id: Uuid,
    pub name: String,
    pub field_type: CustomFieldType,
    #[schema(nullable)]
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub options: Option<Json>,
    pub is_required: bool,
    pub position: i16,
    #[schema(value_type = String, format = "date-time")]
    pub created_at: DateTimeUtc,
}

impl ActiveModelBehavior for ActiveModel {}
