//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "project_statuses")]
#[schema(as = crate::entities::project_statuses::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    pub project_id: Uuid,
    pub name: String,
    pub color: String,
    pub position: i16,
    pub is_default: bool,
    pub is_done_state: bool,
    #[schema(value_type = String, format = "date-time")]
    pub created_at: DateTimeUtc,
}

impl ActiveModelBehavior for ActiveModel {}
