//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: String,
    pub tenant_id: Uuid,
    #[sea_orm(nullable)]
    pub icon_emoji: Option<String>,
    #[sea_orm(nullable)]
    pub icon_url: Option<String>,

    pub key: String,
    pub is_personal: bool,
    #[sea_orm(nullable)]
    pub personal_owner_id: Option<Uuid>,
}

impl ActiveModelBehavior for ActiveModel {}
