//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "projects")]
#[schema(as = crate::entities::projects::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: String,
    #[schema(value_type = String, format = "uuid")]
    pub tenant_id: Uuid,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub icon_emoji: Option<String>,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub icon_url: Option<String>,

    pub key: String,
    #[serde(default)]
    pub is_personal: bool,
    #[sea_orm(nullable)]
    #[schema(value_type = Option<String>, format = "uuid", nullable)]
    pub personal_owner_id: Option<Uuid>,
}

impl ActiveModelBehavior for ActiveModel {}
