//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

use crate::entities::tasks::TaskPriority;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "tasks")]
#[schema(as = crate::entities::tasks::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    pub project_id: Uuid,
    pub seq_id: i32,
    pub title: String,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub description: Option<String>,
    #[schema(value_type = String, format = "uuid")]
    pub status_id: Uuid,
    pub priority: TaskPriority,
    pub progress_pct: i16,
    #[sea_orm(nullable)]
    #[schema(value_type = Option<String>, format = "uuid", nullable)]
    pub parent_task_id: Option<Uuid>,
    #[sea_orm(nullable)]
    #[schema(value_type = Option<String>, format = "uuid", nullable)]
    pub milestone_id: Option<Uuid>,
    #[sea_orm(nullable)]
    #[schema(value_type = Option<String>, format = "uuid", nullable)]
    pub sprint_id: Option<Uuid>,
    #[sea_orm(nullable)]
    #[schema(value_type = Option<String>, format = "date-time", nullable)]
    pub soft_deadline: Option<DateTimeUtc>,
    #[sea_orm(nullable)]
    #[schema(value_type = Option<String>, format = "date-time", nullable)]
    pub hard_deadline: Option<DateTimeUtc>,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub estimated_minutes: Option<i32>,
    pub is_archived: bool,
    #[schema(value_type = String, format = "uuid")]
    pub created_by: Uuid,
    #[schema(value_type = String, format = "date-time")]
    pub created_at: DateTimeUtc,
    #[schema(value_type = String, format = "date-time")]
    pub updated_at: DateTimeUtc,
    #[sea_orm(nullable)]
    #[schema(value_type = Option<String>, format = "date-time", nullable)]
    pub completed_at: Option<DateTimeUtc>,
    #[sea_orm(nullable)]
    #[schema(value_type = Option<String>, format = "date-time", nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

impl ActiveModelBehavior for ActiveModel {}
