//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "task_custom_field_values")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub task_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub field_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "field_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project_custom_fields: HasOne<super::project_custom_fields::Entity>,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tasks: HasOne<super::tasks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
