//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use crate::entities::tasks::TaskPriority;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub project_id: Uuid,
    pub seq_id: i32,
    pub title: String,
    #[sea_orm(nullable)]
    pub description: Option<String>,
    pub status_id: Uuid,
    pub priority: TaskPriority,
    pub progress_pct: i16,
    #[sea_orm(nullable)]
    pub parent_task_id: Option<Uuid>,
    #[sea_orm(nullable)]
    pub milestone_id: Option<Uuid>,
    #[sea_orm(nullable)]
    pub sprint_id: Option<Uuid>,
    #[sea_orm(nullable)]
    pub soft_deadline: Option<DateTimeWithTimeZone>,
    #[sea_orm(nullable)]
    pub hard_deadline: Option<DateTimeWithTimeZone>,
    #[sea_orm(nullable)]
    pub estimated_minutes: Option<i32>,
    pub is_archived: bool,
    pub created_by: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(nullable)]
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(nullable)]
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

impl ActiveModelBehavior for ActiveModel {}
