//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "task_custom_field_values")]
#[schema(as = crate::entities::task_custom_field_values::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub task_id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub field_id: Uuid,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub value: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
