//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tenants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub display_id: String,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub icon_url: String,
    pub owner_id: Uuid,
    pub drive_quota_bytes: Option<i64>,
    pub require_2fa: bool,
    #[sea_orm(has_many)]
    pub audit_logs: HasMany<super::audit_logs::Entity>,
    #[sea_orm(has_many)]
    pub drive_files: HasMany<super::drive_files::Entity>,
    #[sea_orm(has_many)]
    pub drive_folders: HasMany<super::drive_folders::Entity>,
    #[sea_orm(has_many)]
    pub personal_tokens: HasMany<super::personal_tokens::Entity>,
    #[sea_orm(has_many)]
    pub projects: HasMany<super::projects::Entity>,
    #[sea_orm(
        belongs_to,
        from = "owner_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
