//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "tenants")]
#[schema(as=crate::entities::tenants::Model)]
pub struct Model {
    #[schema(value_type = String, format="uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub display_id: String,
    pub name: String,
    pub description: String,
    pub icon_url: String,
    #[schema(value_type = String, format="uuid")]
    pub owner_id: Uuid,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub drive_quota_bytes: Option<i64>,
    /// テナントメンバー全員に 2FA 設定を強制する
    pub require_2fa: bool,
}

impl ActiveModelBehavior for ActiveModel {}
