//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tenants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub display_id: String,
    pub name: String,
    pub description: String,
    pub icon_url: String,
    pub owner_id: Uuid,
    #[sea_orm(nullable)]
    pub drive_quota_bytes: Option<i64>,
    pub require_2fa: bool,
}

impl ActiveModelBehavior for ActiveModel {}
