//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "time_logs")]
#[schema(as = crate::entities::time_logs::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    pub task_id: Uuid,
    #[schema(value_type = String, format = "uuid")]
    pub user_id: Uuid,
    pub logged_minutes: i32,
    #[schema(value_type = String, format = "date")]
    pub logged_at: Date,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub note: Option<String>,
    #[schema(value_type = String, format = "date-time")]
    pub created_at: DateTimeUtc,
}

impl ActiveModelBehavior for ActiveModel {}
