//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub username: String,
    #[sea_orm(nullable)]
    pub bio: Option<String>,
    #[sea_orm(nullable)]
    pub avatar_url: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub email_verified: bool,
    #[sea_orm(nullable)]
    pub password_hash: Option<String>,
    pub is_admin: bool,
    pub is_suspended: bool,
    #[sea_orm(nullable)]
    pub sessions_revoked_at: Option<DateTimeWithTimeZone>,
    pub totp_enabled: bool,
}

impl ActiveModelBehavior for ActiveModel {}
