//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, utoipa::ToSchema)]
#[sea_orm(table_name = "users")]
#[schema(as = crate::entities::users::Model)]
pub struct Model {
    #[schema(value_type = String, format = "uuid")]
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[schema(value_type = String, format = "username")]
    pub username: String,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub bio: Option<String>,
    #[sea_orm(nullable)]
    #[schema(nullable)]
    pub avatar_url: Option<String>,
    #[schema(value_type = String, format = "email")]
    #[sea_orm(unique)]
    pub email: String,
    /// メールアドレスの確認が済んでいるかどうか
    pub email_verified: bool,
    #[sea_orm(nullable)]
    #[schema(ignore)]
    #[serde(skip_serializing)]
    pub password_hash: Option<String>,
    pub is_admin: bool,
    pub is_suspended: bool,
    #[sea_orm(nullable)]
    #[schema(ignore)]
    #[serde(skip_serializing)]
    pub sessions_revoked_at: Option<DateTimeUtc>,
    /// TOTP 2FA が有効か（`totp_credentials.is_verified` とセットで有効扱い）。
    /// 更新は `handlers::auth_2fa` 経由の ActiveModel のみとし、他モジュールから直接書き換えないこと。
    pub totp_enabled: bool,
}

impl ActiveModelBehavior for ActiveModel {}
