//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub username: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar_url: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub email_verified: bool,
    pub password_hash: Option<String>,
    pub is_admin: bool,
    pub is_suspended: bool,
    pub sessions_revoked_at: Option<DateTimeWithTimeZone>,
    pub totp_enabled: bool,
    #[sea_orm(has_many)]
    pub audit_logs: HasMany<super::audit_logs::Entity>,
    #[sea_orm(has_many)]
    pub drive_files: HasMany<super::drive_files::Entity>,
    #[sea_orm(has_many)]
    pub drive_folders: HasMany<super::drive_folders::Entity>,
    #[sea_orm(has_many)]
    pub github_integrations: HasMany<super::github_integrations::Entity>,
    #[sea_orm(has_many)]
    pub milestones: HasMany<super::milestones::Entity>,
    #[sea_orm(has_many)]
    pub notifications: HasMany<super::notifications::Entity>,
    #[sea_orm(has_many)]
    pub oauth_connections: HasMany<super::oauth_connections::Entity>,
    #[sea_orm(has_many)]
    pub passkeys: HasMany<super::passkeys::Entity>,
    #[sea_orm(has_many)]
    pub personal_tokens: HasMany<super::personal_tokens::Entity>,
    #[sea_orm(has_many)]
    pub project_members: HasMany<super::project_members::Entity>,
    #[sea_orm(has_many)]
    pub project_task_views: HasMany<super::project_task_views::Entity>,
    #[sea_orm(has_many)]
    pub recovery_codes: HasMany<super::recovery_codes::Entity>,
    #[sea_orm(has_many)]
    pub sprints: HasMany<super::sprints::Entity>,
    #[sea_orm(has_many)]
    pub task_activities: HasMany<super::task_activities::Entity>,
    #[sea_orm(has_many)]
    pub task_assignees: HasMany<super::task_assignees::Entity>,
    #[sea_orm(has_many)]
    pub task_attachments: HasMany<super::task_attachments::Entity>,
    #[sea_orm(has_many)]
    pub task_comments: HasMany<super::task_comments::Entity>,
    #[sea_orm(has_many)]
    pub task_timers: HasMany<super::task_timers::Entity>,
    #[sea_orm(has_many)]
    pub task_watchers: HasMany<super::task_watchers::Entity>,
    #[sea_orm(has_many)]
    pub tasks: HasMany<super::tasks::Entity>,
    #[sea_orm(has_many)]
    pub tenants: HasMany<super::tenants::Entity>,
    #[sea_orm(has_many)]
    pub time_logs: HasMany<super::time_logs::Entity>,
    #[sea_orm(has_one)]
    pub totp_credentials: HasOne<super::totp_credentials::Entity>,
    #[sea_orm(has_many, via = "notification_settings")]
    pub projects: HasMany<super::projects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
